workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    environment:
      java: 21
      node: 22
    scripts:
      - name: Cek versi Java
        script: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
      - name: Pasang dependensi
        script: npm ci
      - name: Pasang dependensi
        script: npm ci
      - name: Sinkronkan Capacitor ke project Android
        script: npx cap sync android
      - name: Build debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

  workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    environment:
      java: 21
      node: 22
    scripts:
      - name: Cek versi Java
        script: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
      - name: Pasang dependensi
        script: npm ci
      - name: Pasang dependensi
        script: npm ci
      - name: Sinkronkan Capacitor ke project Android
        script: npx cap sync android
      - name: Build debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk


  android-release:
    name: Android Release AAB
    max_build_duration: 30
    environment:
      java: 21
      node: 22
      android_signing:
        - juragan_keystore
    scripts:
      - name: Pasang dependensi
        script: npm ci
      - name: Sinkronkan Capacitor ke project Android
        script: npx cap sync android
      - name: Build release AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab


